CREATE DATABASE IF NOT EXISTS raianzu_workshop;
USE raianzu_workshop;

CREATE TABLE services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100),
  deskripsi TEXT,
  harga INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE parts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100),
  deskripsi TEXT DEFAULT NULL,
  stok INT,
  harga INT,
  image VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100),
  email VARCHAR(100),
  pesan TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Users table untuk admin
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
